// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfhgekyriwabgksreszy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1maGdla3lyaXdhYmdrc3Jlc3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjEwMjUsImV4cCI6MjA3MDQ5NzAyNX0.zUwsImMyg8vZNeGhZouhFAL6ZDvcjH5vXVOOWXNRbG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});